id: I6BBA9020
legacy_id: P009333
ocr_import_info:
  bdrc_scan_id: W9366
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T20:01:19'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-04T05:09:58.956218+00:00'
last_modified: 2022-09-04 13:10:23.299523
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W9366
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW9366
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དམ་ཅན་བསྟན་སྲུང་རྒྱ་མཚོའི་རྣམ་ཐར།༼དབུ་ཅན་བྲིས་མ།༽
  author: འོལ་དགའ་རྗེ་དྲུང ༠༣་བཞད་པའི་རྡོ་རྗེ།
statistics:
  ocr_word_mean_confidence_index: 0.802500159879203
  ocr_word_median_confidence_index: 0.8799999952316284
quality: null
bases:
  I0594:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0594
      total_pages: 338
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I0594.txt
    statistics:
      ocr_word_median_confidence_index: 0.8799999952316284
      ocr_word_mean_confidence_index: 0.809940363530954
    legacy_id: v002
  I0593:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0593
      total_pages: 395
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I0593.txt
    statistics:
      ocr_word_median_confidence_index: 0.8700000047683716
      ocr_word_mean_confidence_index: 0.7952641279629371
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
