id: I6BBA9020
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T20:03:31+00:00'
last_modified: '2022-06-08T10:16:22.209383+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W9366
  title: དམ་ཅན་བསྟན་སྲུང་རྒྱ་མཚོའི་རྣམ་ཐར།༼དབུ་ཅན་བྲིས་མ།༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    262F:
      image_group_id: I0593
      title: ''
      total_pages: 395
      order: 1
      base_file: 262F.txt
    501F:
      image_group_id: I0594
      title: ''
      total_pages: 338
      order: 2
      base_file: 501F.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
